---
- name: Install cups
  apt:
    name:
      - cups
      - cups-client
    state: present
  become: true

- name: Copy printers.conf
  copy:
    src: printer/printers.conf
    dest: /etc/cups/
  become: true

- name: Restart cups
  systemd:
    name: cups.service
    state: restarted
  become: true
