---
- name: Install asterisk
  apt:
    name: asterisk
    state: present
  become: true

- name: Copy sip.conf
  copy:
    src: asterisk/sip.conf
    dest: /var/lib/asterisk/sounds/


- name: Copy extensions.conf
  copy:
    src: asterisk/extensions.conf
    dest: /etc/asterisk/

- name: Copy voices
  copy:
    src: asterisk/custom
    dest: /var/lib/asterisk/sounds/custom

- name: Restart asterisk
  systemd:
    name: asterisk
    state: restarted
