---
- name: Install strongswan
  ansible.builtin.apt:
    name:
      - strongswan
      - strongswan-pki
      - strongswan-swanctl
      - libstrongswan-extra-plugins
      - libcharon-extra-plugins
      - libcharon-extauth-plugins
      - libtss2-tcti-tabrmd0
    state: present
  become: true

- name: Copy swanctl.conf
  copy:
    src: strongswan/swanctl.conf
    dest: /etc/swanctl/
    mode: 0644
  become: true

- name: Copy ca cert
  copy:
    src: certificate/strongSwan/ca-cert.pem
    dest: /etc/swanctl/x509ca/
    mode: 0700
  become: true

- name: Copy server cert
  copy:
    src: certificate/strongSwan/server-cert.pem
    dest: /etc/swanctl/x509/
    mode: 0700
  become: true

- name: Copy server key
  copy:
    src: certificate/strongSwan/server-key.pem
    dest: /etc/swanctl/private/
    mode: 0700
  become: true

- name: Copy ca key
  copy:
    src: certificate/strongSwan/ca-key.pem
    dest: /etc/swanctl/private/
    mode: 0700
  become: true

- name: Copy client key
  copy:
    src: certificate/strongSwan/client-key.pem
    dest: /etc/swanctl/rsa/
    mode: 0700
  become: true

- name: Reload strongSwan
  command:
    cmd: swanctl --load-all

- name: Allow port 500
  ufw:
    rule: allow
    state: enabled
    proto: udp
    to_port: 500

- name: Allow port 4500
  ufw:
    rule: allow
    state: enabled
    proto: udp
    to_port: 4500

- name: Copy ufw before.rules
  copy:
    src: ufw/before.rules
    dest: /etc/ufw/
    mode: 0640
  become: true

- name: Copy ufw sysctl.conf
  copy:
    src: ufw/sysctl.conf
    dest: /etc/ufw/
    mode: 0644
  become: true

- name: Restart ufw
  ufw:
    state: enabled
