---
- name: Install strongswan
  ansible.builtin.apt:
    name:
      - strongswan
      - strongswan-pki
      - strongswan-swanctl
      - libstrongswan-extra-plugins
      - libcharon-extra-plugins
      - libcharon-extauth-plugins
    state: present
  become: true

- name: Copy swanctl.conf
  copy:
    src: strongswan/swanctl.conf
    dest: /etc/swanctl/
    mode: 0644
  become: true
