---
- name: Install nginx
  apt:
    name:
      - nginx
    state: present
  become: true

- name: Allow port 80
  ufw:
    rule: allow
    proto: any
    to_port: 80

- name: Copy nginx.conf
  copy:
    src: nginx/nginx.conf
    dest: /etc/nginx/
