---
- name: Install nginx
  apt:
    name:
      - nginx
    state: present
  become: true

- name: Copy nginx.conf
  copy:
    src: nginx/next.conf
    dest: /etc/nginx/conf.d/

- name: get last tag name
  shell: git describe --abbrev=0 --tags
  register: tag

- name: Unarchive web
  unarchive:
    src: https://github.com/sizumita/rabbit_house.smdr.io/releases/download/{{ tag.stdout }}/out.zip
    dest: /var/www/
    remote_src: yes
  when: tag.changed

- name: restart nginx
  systemd:
    state: restarted
    name: nginx
  become: true
