---
- name: Install dnsmasq
  apt:
    name:
      - dnsmasq
    state: present
  become: true

- name: Write dnsmasq conf
  blockinfile:
    path: /etc/dnsmasq.conf
    block: |
      listen-address=172.16.20.1
      resolv-file=/etc/dnsmasq_resolv.conf
      log-queries
      #no-hosts
      addn-hosts=/etc/hosts_dnsmasq
      bind-interfaces
      conf-file=/etc/dnsmasq.rabbit-house.conf
      interface=gsnet

- name: Copy dnsmasq_resolv.conf
  copy:
    src: dnsmasq/dnsmasq_resolv.conf
    dest: /etc/dnsmasq_resolv.conf
    mode: 0644
  become: true

- name: Copy hosts_dnsmasq
  copy:
    src: dnsmasq/hosts_dnsmasq
    dest: /etc/hosts_dnsmasq
    mode: 0644
  become: true

- name: Copy dnsmasq_adblock.sh
  copy:
    src: dnsmasq/dnsmasq_adblock.sh
    dest: /opt/
  become: true

- name: Copy additional_hosts.txt
  copy:
    src: dnsmasq/additional_hosts.txt
    dest: /opt/
  become: true

- name: Copy dnsmasq_adblock.service
  copy:
    src: dnsmasq/dnsmasq_adblock.service
    dest: /etc/systemd/system/
  become: true

- name: Copy dnsmasq_adblock.timer
  copy:
    src: dnsmasq/dnsmasq_adblock.timer
    dest: /etc/systemd/system/
  become: true

- name: Copy 99-rabbit-house.yaml
  copy:
    src: dnsmasq/99-rabbit-house.yaml
    dest: /etc/netplan/
  become: true

- name: Restart netplan
  command:
    cmd: netplan apply
  become: true

- name: Enable and restart adblock
  systemd:
    name: dnsmasq_adblock
    state: restarted
    enabled: true
  become: true

- name: Allow port 53
  ufw:
    rule: allow
    state: enabled
    proto: any
    to_port: 53

- name: Restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: true

- name: Restart systemd-resolve
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
