#!/bin/sh
ip link add br0 type bridge
ip link set br0 up
ip link set $INTERFACE up
ip link set dev $INTERFACE master br0
ip link set dev eth1 master br0
ip addr add 10.22.0.1/8 dev br0
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables-restore < /etc/tinc/gsnet/nat.iptables
iptables -t nat -A POSTROUTING -d 10.0.0.0/8 -o br0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
