---
- name: Update package manager
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: latest
  become: yes

- name: Setup tinc
  import_role: name=setup_tinc
  tags: tinc

- name: Setup strongswan
  import_rule: name=setup_strongswan
  tags: swan
