---
- name: Update package manager
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: latest
  become: yes

- name: Allow port 22
  ufw:
    rule: allow
    state: enabled
    proto: any
    to_port: 22

- name: Setup tinc
  import_role: name=setup_tinc
  tags: tinc

- name: Setup strongswan
  import_role: name=setup_strongswan
  tags: swan

- name: Setup asterisk
  import_role: name=setup_asterisk
  tags: asterisk

- name: Setup nginx
  import_role: name=setup_nginx
  tags: nginx

- name: Setup printer
  import_role: name=setup_printer
  tags: printer

- name: Setup dns
  import_role: name=setup_dnsmasq
  tags: dns

- name: Setup scanner
  import_role: name=setup_gsnet_scanner
  tags: scanner

- name: enable ufw
  systemd:
    name: ufw.service
    enabled: true
